Repository nolanfrb/42sh, pull requests merged in 2025-05, with the labels that each got.

#79 feat(inhibitors): add simple and double quote inhibit handling
  include/inhibitors.h
  src.list
  src/lexer/handle_delimiter.c
  src/lexer/handle_inhibitors.c
  src/lexer/lexer.c
  src_for_tests.list
  tests/tests
Labels: enhancement

#82 Fix/double left redirection
  src/command_execution/execute_command.c
  src/main_loop/process_command.c
  tests/tests
Labels: hotfix

#85 fix(tester): display test output on failure for better debugging
  .github/workflows/tester.yml
Labels: ci

#83 refactor(globbings): restructure globbing functions and introduce utility functions
  include/globbings.h
  src.list
  src/command_execution/pipe/execute_pipe_command.c
  src/globbings/get_directory.c
  src/globbings/get_file.c
  src/globbings/globbings.c
  src/globbings/globbings_utils.c
  src_for_tests.list
  tests/globbings/test_directory/test
  tests/globbings/test_globbings_getdirectory.c
  tests/globbings/test_globbings_getfiles.c
  tests/globbings/test_globbings_main_function.c
  tests/tests
  tests_src.list
Labels: hotfix

#74 feat(line-editing): implement basic history navigation with arrow keys
  Makefile
  include/line_editing.h
  include/shell.h
  src.list
  src/line_editing/escape_mappings.c
  src/line_editing/handlers.c
  src/line_editing/read_command_line.c
  src/line_editing/terminal_control.c
  src/main.c
  src/main_loop/handle_user_input.c
  src_for_tests.list
  tests/env/test_env_free.c
  tests/parser/tests_ast_build.c
Labels: feature

#97 fix(print_env_variable): improve handling of special variable '$?'
  src/builtins/echo_utils.c
Labels: feature

#98 test(tests): add new test cases for setenv, subshells, and heredoc features
  tests/tests
Labels: ci

#99 fix: memory corruption due to buffer clearing
  include/line_editing.h
  include/shell.h
  src/builtins/builtin_exit.c
  src/line_editing/handlers.c
  src/line_editing/read_command_line.c
  src/line_editing/terminal_control.c
Labels: hotfix

#100 feat(builtins): add `set`, `unset`, and `get` commands with unit tests for local variable management
  include/builtins.h
  src.list
  src/builtins/builtin_get.c
  src/builtins/builtin_set.c
  src/builtins/builtin_unset_local.c
  src/builtins/builtins.c
  src_for_tests.list
  tests/builtins/test_builtin_set.c
  tests/builtins/test_bultin_get.c
  tests_src.list
Labels: feature

#101 feat(prompt): add dynamic prompt with hostname and current directory
  include/shell.h
  src.list
  src/builtins/builtin_env.c
  src/main.c
  src/utils/display_prompt.c
  src/utils/gethostname.c
  src_for_tests.list
Labels: feature

#103 feat(variables): add local / env variable handling in prompt
  include/chain.h
  include/command.h
  include/inhibitors.h
  include/lexer.h
  include/utils.h
  src.list
  src/command_execution/get_command_path.c
  src/lexer/add_token.c
  src/lexer/build_tokens.c
  src/lexer/count_words.c
  src/lexer/extract_word.c
  src/lexer/factory/process_character.c
  src/lexer/free/free_lexer.c
  src/lexer/handle_delimiter.c
  src/lexer/handle_inhibitors.c
  src/lexer/handle_special_token.c
  src/lexer/handler/delimiters/handle_parenthesis.c
  src/lexer/handler/delimiters/handle_special_chars.c
  src/lexer/handler/delimiters/is_special_char.c
  src/lexer/handler/delimiters/special_chars.c
  src/lexer/handler/inhibitors/handle_inhibitor.c
  src/lexer/handler/inhibitors/is_inhibitor.c
  src/lexer/handler/variables/handle_variables.c
  src/lexer/handler/variables/parse_variables_format.c
  src/lexer/handler/variables/process_variables.c
  src/lexer/initialization/lexer_init.c
  src/lexer/is_delimiter.c
  src/lexer/lexer.c
  src/lexer/lexer_create.c
  src/lexer/lexer_to_string.c
  src/lexer/utils/display_lexer.c
  src/lexer/utils/is_type.c
  src/lexer/utils/is_whitespace.c
  src/lexer/utils/token_matching.c
  src/linked_list/chain.c
  src/main_loop/handle_user_input.c
  src/main_loop/user_input_error_handling.c
  src/utils/strcat.c
  src_for_tests.list
  tests/lexer/test_check_special_token.c
  tests/lexer/test_count_words.c
  tests/lexer/test_extract_word.c
  tests/lexer/test_handle_delimiter.c
  tests/lexer/test_handle_special_token.c
  tests/lexer/test_lexer.c
  tests/parser/tests_redirect.c
  tests/tests
  tests/utils/tests_strcat.c
  tests_src.list
Labels: feature

#102 fix(shell): improve prompt handling and standardize hostname fallback
  src/line_editing/handlers.c
  src/utils/gethostname.c
Labels: hotfix

#86 feat(alias): add support for user-defined command aliases
  include/alias.h
  include/ast.h
  include/builtins.h
  include/command.h
  include/shell.h
  src.list
  src/alias/count_aliases.c
  src/alias/extract_alias.c
  src/alias/free_alias.c
  src/alias/init_alias.c
  src/alias/load_alias.c
  src/alias/parse_alias_args.c
  src/alias/print_alias.c
  src/alias/search_alias.c
  src/builtins/builtin_alias.c
  src/builtins/builtin_unalias.c
  src/builtins/builtins.c
  src/command_execution/execute_command.c
  src/env/env_free.c
  src/env/env_init.c
  src/main.c
  src/main_loop/built_ast_struct.c
  src/parser/free_ast.c
  src/parser/parse_alias_file.c
  src/utils/build_str.c
  src/utils/get_home_directory.c
  src/utils/handle_user_input.c
  src_for_tests.list
  tests/env/test_env_free.c
  tests/parser/tests_redirect.c
  tests/tests
Labels: feature

#104 refactor(lexer): improve error handling and code organization in hand…
  src/lexer/handler/inhibitors/handle_inhibitor.c
Labels: refactor

#105 refactor(handlers): remove unused write_prompt function
  src/line_editing/handlers.c
Labels: hotfix

#106 fix(builtin_exit): ensure exit message is flushed before exiting
  src/builtins/builtin_exit.c
Labels: hotfix
