Repository nolanfrb/42sh, pull requests merged in 2025-04, with the labels that each got.

#2 docs(readme): explain 42sh project with readme
  README.md
Labels: documentation

#3 ci: add build / test / push pipeline
  .github/workflows/build-and-test.yml
  .gitignore
Labels: enhancement

#28 feat(ast): add all parsing functions with unit tests for each functions
  Makefile
  include/ast.h
  include/lexer.h
  include/shell.h
  src.list
  src/lexer/check_special_token.c
  src/lexer/count_words.c
  src/lexer/extract_word.c
  src/lexer/handle_delimiter.c
  src/lexer/handle_special_token.c
  src/lexer/is_delimiter.c
  src/lexer/lexer.c
  src/parser/parse_and_or.c
  src/parser/parse_command.c
  src/parser/parse_pipes.c
  src/parser/parse_redirect.c
  src/parser/parse_sequence.c
  src/parser/parse_subshell.c
  src/parser/utils/is_operator.c
  tests/parser/tests_and_or.c
  tests/parser/tests_commands.c
  tests/parser/tests_operators.c
  tests/parser/tests_pipes.c
  tests/parser/tests_redirect.c
  tests/parser/tests_sequence.c
  tests/parser/tests_subshell.c
  tests_src.list
Labels: enhancement

#32 Lexer Test Coverage
  .gitignore
  Makefile
  tests/lexer/test_check_special_token.c
  tests/lexer/test_count_words.c
  tests/lexer/test_extract_word.c
  tests/lexer/test_handle_delimiter.c
  tests/lexer/test_handle_special_token.c
  tests/lexer/test_lexer.c
  tests_src.list
Labels: enhancement

#38 Add Environment Variable Management: Core Functions and Unit Tests
  include/env.h
  include/shell.h
  src.list
  src/env/env_free.c
  src/env/env_get.c
  src/env/env_init.c
  src/env/env_set.c
  src/env/env_unset.c
  tests/env/test_env_free.c
  tests/env/test_env_get.c
  tests/env/test_env_init.c
  tests/env/test_env_set.c
  tests/env/test_env_unset.c
  tests_src.list
Labels: enhancement

#31 feat(main loop): add commands execution
  include/shell.h
  src.list
  src/main.c
  src/main_loop/handle_user_input.c
  src/main_loop/process_command.c
Labels: enhancement

#40 feat(command_execution) : add function to execute simple command
  include/ast.h
  include/command.h
  src.list
  src/command_execution/execute_command.c
  src/command_execution/utils.c
  src/main.c
  src/main_loop/process_command.c
Labels: enhancement

#44 refactor(execute_functions): redeclaration of execute_function array
  include/ast.h
  src/main_loop/process_command.c
Labels: enhancement

#41 feat(command_execution) : add command execution for pipe system
  include/command.h
  src.list
  src/command_execution/execute_pipe_command.c
  src/main_loop/process_command.c
Labels: enhancement

#42 feat(command_execution) : add command execution for or (||) option
  include/command.h
  include/shell.h
  src.list
  src/command_execution/execute_command.c
  src/command_execution/execute_or_command.c
  src/main_loop/process_command.c
Labels: enhancement

#43 feat(command_execution) : add function to use the and (&&) option in command execution
  include/command.h
  src.list
  src/command_execution/execute_and_command.c
  src/main_loop/process_command.c
Labels: enhancement

#45 feat(command_execution) : add semi-colons as option in command execution
  include/command.h
  src.list
  src/command_execution/execute_sequence_command.c
  src/main_loop/process_command.c
Labels: enhancement

#46 feat(command_execution) : add redirection as option for command execution
  include/command.h
  include/redirect_cmd.h
  src.list
  src/command_execution/execute_redirect_command.c
  src/main_loop/process_command.c
Labels: enhancement

#53 fix(execute_pipe_command) : Fix waitpid placement in the function
  src/command_execution/execute_pipe_command.c
Labels: hotfix

#59 feat(builtins): implement core built-in shell commands and integration
  include/builtins.h
  include/command.h
  include/shell.h
  src.list
  src/builtins/builtin_cd.c
  src/builtins/builtin_echo.c
  src/builtins/builtin_env.c
  src/builtins/builtin_exit.c
  src/builtins/builtin_setenv.c
  src/builtins/builtin_unsetenv.c
  src/builtins/builtins.c
  src/builtins/echo_utils.c
  src/command_execution/execute_command.c
  src/command_execution/execute_redirect_command.c
  src/command_execution/utils.c
  src/env/env_init.c
  src/main.c
Labels: feature

#60 fix (command_execution): add modifications to the exit code value whe…
  include/command.h
  src/builtins/builtin_setenv.c
  src/builtins/builtin_unsetenv.c
  src/command_execution/execute_command.c
  src/main.c
  src/main_loop/process_command.c
Labels: bug

#61 feat(pipes): implement pipe command execution and parsing
  include/command.h
  src.list
  src/command_execution/pipe/execute_pipe_command.c
  src/command_execution/pipe/get_pipe_command.c
  src/parser/parse_pipes.c
Labels: feature, hotfix

#65 feat(shell): implement command history with expansion support
  include/builtins.h
  include/shell.h
  src.list
  src/builtins/builtin_history.c
  src/builtins/builtins.c
  src/env/env_init.c
  src/main.c
  src/main_loop/handle_user_input.c
Labels: feature

#72 feat(command): add subshell command execution functionality
  include/command.h
  src.list
  src/command_execution/execute_subshell_command.c
  src/main_loop/process_command.c
  src_for_tests.list
Labels: enhancement, feature

#71 refactor: update built_ast_struct to accept shell_info and improve error handling
  include/shell.h
  src/command_execution/execute_command.c
  src/command_execution/pipe/execute_pipe_command.c
  src/main.c
  src/main_loop/handle_user_input.c
  src/parser/parse_redirect.c
Labels: hotfix

#69 feat(globbings): implement file globbing functionality
  include/globbings.h
  src.list
  src/command_execution/execute_command.c
  src/globbings/get_directory.c
  src/globbings/get_file.c
  src/globbings/globbings.c
  src/main.c
  src_for_tests.list
  tester/test_main.c
  tests/globbings/test_directory/test
  tests/globbings/test_globbings_getdirectory.c
  tests/globbings/test_globbings_getfiles.c
  tests/globbings/test_globbings_main_function.c
  tests_src.list
Labels: enhancement, feature

#73 fix(command_execution): update execute_and function to return the exit code of the first command
  src/command_execution/execute_and_command.c
Labels: hotfix

#63 tests: add ast building and command reading test
  tests/parser/tests_ast_build.c
  tests/utils/tests_strcat.c
  tests_src.list
Labels: tests

#76 fix(pipe): fix cleaning pipe at run time
  src/command_execution/pipe/execute_pipe_command.c
  tests/tests
Labels: hotfix

#75 hotfix(path_handling): handle path environnement variable on /commands
  include/env.h
  src.list
  src/builtins/builtin_env.c
  src/command_execution/get_command_path.c
  src/command_execution/utils/path.c
  src_for_tests.list
Labels: hotfix

#81 refactor(pipe): enhance pipe handling with new state management and initialization functions
  include/command.h
  src.list
  src/command_execution/pipe/execute_pipe_command.c
  src/command_execution/pipe/init_command.c
  src/command_execution/pipe/setup_pipe.c
  src_for_tests.list
  tests/tests
Labels: hotfix
